NacionalLibrary_Application/Controllers/BooksController.cs
using AutoMapper;
using Infrastructure.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NacionalLibrary_Application.Models;
using Services.Interfaces;

namespace NacionalLibrary_Application.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IEditorialService _editorialService;
        private readonly IAuthorService _authorService;
        private readonly IMapper _mapper;

        public BooksController(IBookService bookService, IEditorialService editorialService, IMapper mapper, IAuthorService authorService)
        {
            _bookService = bookService;
            _editorialService = editorialService;
            _mapper = mapper;
            _authorService = authorService;
        }

        public async Task<IActionResult> Index()
        {
            var books = await _bookService.GetAllAsync();
            List<BookModel> model = _mapper.Map<List<BookModel>>(books);
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            List<Editorial> editorialsEntities = await _editorialService.GetAllAsync();
            ViewBag.Editorials = _mapper.Map<List<EditorialModel>>(editorialsEntities);

            List<Author> authorsEntities = await _authorService.GetAllAsync();
            ViewBag.Authors = _mapper.Map<List<AuthorModel>>(authorsEntities);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BookModel model)
        {
            if (!ModelState.IsValid)
            {
                List<Editorial> editorialsEntities = await _editorialService.GetAllAsync();
                ViewBag.Editorials = _mapper.Map<List<EditorialModel>>(editorialsEntities);

                List<Author> authorsEntities = await _authorService.GetAllAsync();
                ViewBag.Authors = _mapper.Map<List<AuthorModel>>(authorsEntities);
                return View(model);
            }

            var bookEntity = _mapper.Map<Book>(model);
            bookEntity.AuthorBooks = new List<AuthorBook>();
            foreach (var authorId in model.SelectedAuthorIds)
            {
                
                bookEntity.AuthorBooks.Add(new AuthorBook { AuthorId = authorId });
            }

            await _bookService.CreateAsync(bookEntity);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var bookEntity = await _bookService.GetByIdAsync(id);
            if (bookEntity == null)
                return NotFound();

            var model = _mapper.Map<BookModel>(bookEntity);

            var editorialsEntities = await _editorialService.GetAllAsync();
            ViewBag.EditorialsSelect = new SelectList(
                _mapper.Map<List<EditorialModel>>(editorialsEntities),
                "Id",    
                "Name",  
                model.EditorialId 
            );

            var authorsEntities = await _authorService.GetAllAsync();
            ViewBag.AuthorsSelect = new MultiSelectList(
                _mapper.Map<List<AuthorModel>>(authorsEntities),
                "Id",    
                "FullName",
                model.BookAuthors.Select(ba => ba.AuthorId)
            );

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, BookModel model)
        {
            if (id != model.Id)
                return BadRequest();

            if (!ModelState.IsValid)
            {
                List<Editorial> editorialsEntities = await _editorialService.GetAllAsync();
                ViewBag.Editorials = _mapper.Map<List<EditorialModel>>(editorialsEntities);

                List<Author> authorsEntities = await _authorService.GetAllAsync();
                ViewBag.Authors = _mapper.Map<List<AuthorModel>>(authorsEntities);

                return View(model);
            }

            var bookEntity = await _bookService.GetByIdAsync(id);
            if (bookEntity == null)
                return NotFound();

            _mapper.Map(model, bookEntity);

            bookEntity.AuthorBooks!
                    .Where(ab => !model.SelectedAuthorIds.Contains(ab.AuthorId))
                    .ToList()
                    .ForEach(ab => bookEntity.AuthorBooks!.Remove(ab));

            var existingIds = bookEntity.AuthorBooks!.Select(ab => ab.AuthorId).ToList();
            foreach (var authorId in model.SelectedAuthorIds)
            {
                if (!existingIds.Contains(authorId))
                {
                    bookEntity.AuthorBooks!.Add(new AuthorBook { AuthorId = authorId });
                }
            }

            await _bookService.UpdateAsync(bookEntity);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var book = await _bookService.GetByIdAsync(id);
            if (book == null)
                return NotFound();

            await _bookService.DeleteAsync(id);
            return Ok();
        }
    }
}

NacionalLibrary_Application/Controllers/EditorialsController.cs
using AutoMapper;
using Infrastructure.Entities;
using Microsoft.AspNetCore.Mvc;
using NacionalLibrary_Application.Models;
using Services.Interfaces;

namespace NacionalLibrary_Application.Controllers
{
    public class EditorialsController : Controller
    {
        private readonly IEditorialService _editorialService;
        private readonly IMapper _mapper;

        public EditorialsController(IEditorialService editorialService, IMapper mapper)
        {
            _editorialService = editorialService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var editorials = await _editorialService.GetAllAsync();
            List<EditorialModel> model = _mapper.Map<List<EditorialModel>>(editorials);
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Editorial model)
        {
            if (!ModelState.IsValid)
                return View(model);

            await _editorialService.CreateAsync(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var editorial = await _editorialService.GetByIdAsync(id);
            if (editorial == null)
                return NotFound();

            var model = _mapper.Map<EditorialModel>(editorial);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditorialModel model)
        {
            if (id != model.Id)
                return BadRequest();

            if (!ModelState.IsValid)
                return View(model);

            var editorialEntity = await _editorialService.GetByIdAsync(id);
            if (editorialEntity == null)
                return NotFound();

            _mapper.Map(model, editorialEntity);

            await _editorialService.UpdateAsync(editorialEntity);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var editorial = await _editorialService.GetByIdAsync(id);
            if (editorial == null)
                return NotFound();

            if (editorial.Books!.Any())
                return BadRequest("Cannot delete this editorial because it has books assigned.");

            await _editorialService.DeleteAsync(id);
            return Ok();
        }
    }
}

NacionalLibrary_Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NationalLibrary_Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">NationalLibrary_Application</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Editorials" asp-action="Index">Editorials</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - NationalLibrary_Application - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

    
</body>
</html>